### ISSUE TITLE
Request: Grass

### ISSUE THREAD

**Issue by benjamin5896** [bvlinsky/home-assistant-passive-income#1]
Hi, thank you for all the work you've done on these addons, these have really helped me. 

I was just wondering if it would be possible for you to create an addon for the bandwidth sharing service Grass? There is already a pre-made docker image for it {mrcolorrain/grass-node}. If you could integrate this into the repo I would be very grateful.

**Comment by bvlinsky** [comment]
Hi, no problem, I will add support for this service.

Expect an update soon.

**Comment by bvlinsky** [comment]
Done in https://github.com/bvlinsky/home-assistant-passive-income/pull/4
